### ISSUE TITLE
Unable to add antagonist to the reservoir

### ISSUE THREAD

**Issue by DrJo-Bangor** [johndempster/ObSimFMX#3]
I want to add antagonists to the reservoir instead of the organ bath. The help contents say to select reservoir instead of organ bath when adding antagonists but this doesn't seem to be an option. 

![image](https://github.com/user-attachments/assets/bc963cd6-8bf8-4920-a3a3-0273f59c3242)

**Comment by johndempster** [comment]
Dear Jo,
I have fixed this problem and put an updated version (V4.1.3) on to GitHub.
John Dempster
